"""chat index

Revision ID: 6b8668e559b4
Revises: d56203dcc1db
Create Date: 2026-06-17 14:55:51.817766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8668e559b4'
down_revision: Union[str, Sequence[str], None] = 'd56203dcc1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_updated_at'), 'chats', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_updated_at'), table_name='chats')
    # ### end Alembic commands ###
